import {useCallback,useEffect,useRef,useState} from 'react';import {DevToolsTransport} from '../protocol/transport';import type {ConnectionStage,DiagnosticsSnapshot,DomainInfo,HostInfo,InputSnapshot,Operation,ProtocolError,ResourceSnapshot} from '../protocol/types';
const emptyDiagnostics:DiagnosticsSnapshot={status:{},activities:[],metrics:[]}; const emptyResources:ResourceSnapshot={catalog:[],roots:[],allLoaded:[]};
export function useDevTools(transport=new DevToolsTransport()){
 const transportRef=useRef(transport), generation=useRef(0), retryTimer=useRef<number|undefined>(undefined), connectRef=useRef<(manual?:boolean)=>Promise<void>>(async()=>{}); const [stage,setStage]=useState<ConnectionStage>('idle'),[reason,setReason]=useState(''),[hosts,setHosts]=useState<HostInfo[]>([]),[hostId,setHostIdState]=useState(''),[domains,setDomains]=useState<DomainInfo[]>([]),[input,setInput]=useState<InputSnapshot>({}),[resources,setResources]=useState(emptyResources),[diagnostics,setDiagnostics]=useState(emptyDiagnostics),[operations,setOperations]=useState<Operation[]>([]),[attempts,setAttempts]=useState(0),[lastMessage,setLastMessage]=useState<Date>();
 const track=useCallback(async<T,>(name:string,target:string,run:()=>Promise<T>)=>{const id=crypto.randomUUID(),start=performance.now(),startedAt=new Date().toISOString();setOperations(v=>[{id,name,target,status:'running' as const,startedAt},...v].slice(0,100));try{const result=await run();setOperations(v=>v.map(x=>x.id===id?{...x,status:'succeeded',finishedAt:new Date().toISOString(),durationMs:performance.now()-start,result}:x));return result}catch(value){const error=value as ProtocolError;setOperations(v=>v.map(x=>x.id===id?{...x,status:error.code==='canceled'?'canceled':'failed',finishedAt:new Date().toISOString(),durationMs:performance.now()-start,error}:x));throw error}},[]);
 const refresh=useCallback(async(selected=hostId)=>{if(!selected)return;const t=transportRef.current;const [d,i,r,diag]=await Promise.all([t.domains(selected),t.invoke<InputSnapshot>(selected,'input','getState','query'),t.invoke<ResourceSnapshot>(selected,'resources','getState','query'),t.invoke<DiagnosticsSnapshot>(selected,'diagnostics','getSnapshot','query')]);setDomains(d);setInput(i);setResources(r);setDiagnostics(diag)},[hostId]);
 const connect=useCallback(async(manual=false)=>{window.clearTimeout(retryTimer.current);const token=++generation.current;setStage('server-connecting');setReason('');try{const t=transportRef.current;await t.connect();if(token!==generation.current)return;setStage('server-connected');setStage('negotiating');const negotiation=await t.negotiate();if(!negotiation.supportedVersions.includes('1.0')){setStage('incompatible');setReason(`Server supports ${negotiation.supportedVersions.join(', ')}`);return}const available=await t.hosts();setHosts(available);if(!available.length){setStage('host-selecting');setReason('No runtime host is connected.');return}const selected=available.some(h=>h.hostId===hostId)?hostId:available[0].hostId;setHostIdState(selected);await refresh(selected);for(const [domain,feature] of [['input','inputChanged'],['resources','operationChanged'],['diagnostics','updated']])await t.subscribe(selected,domain,feature);setStage('host-connected');setAttempts(0)}catch(value){if(token!==generation.current)return;setStage('disconnected');setReason((value as ProtocolError).message??String(value));if(!manual){setAttempts(v=>{const next=v+1;retryTimer.current=window.setTimeout(()=>void connectRef.current(),Math.min(30000,500*2**Math.min(next,6)));return next})}}},[hostId,refresh]);
 useEffect(()=>{connectRef.current=connect},[connect]);
 const selectHost=useCallback(async(id:string)=>{generation.current++;transportRef.current.close('host switch');setHostIdState(id);setDomains([]);setInput({});setResources(emptyResources);setDiagnostics(emptyDiagnostics);await connect(true)},[connect]);
 const invoke=useCallback(<T,>(domain:string,feature:string,kind:'query'|'command',params:unknown={})=>track(`${domain}/${feature}`,hostId,()=>transportRef.current.invoke<T>(hostId,domain,feature,kind,params)),[hostId,track]);
 useEffect(()=>{const t=transportRef.current;const event=(e:Event)=>{setLastMessage(new Date());const value=(e as CustomEvent).detail;if(value.domain==='input')setInput(value.params.snapshot);if(value.domain==='resources')setResources(value.params.snapshot);if(value.domain==='diagnostics')setDiagnostics({status:value.params.status,activities:value.params.activities,metrics:value.params.metrics})};t.addEventListener('protocol-event',event);queueMicrotask(()=>void connect());return()=>{generation.current++;window.clearTimeout(retryTimer.current);t.removeEventListener('protocol-event',event);t.close()}},[]);
 return{stage,reason,hosts,hostId,domains,input,resources,diagnostics,operations,attempts,lastMessage,connect:()=>connect(true),selectHost,refresh:()=>refresh(),invoke,setInput,setResources,setDiagnostics};
}
