<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Graphics Vulkan device capabilities.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Lumyte.Graphics.Shared" />
    <ProjectReference Include="../Lumyte.Graphics.Shared/Lumyte.Graphics.Shared.csproj" />
    <ProjectReference Include="../Lumyte.Graphics.Abstractions/Lumyte.Graphics.Abstractions.csproj" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
