<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Reusable two-dimensional rendering components for Lumyte.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lumyte.Graphics\Lumyte.Graphics.csproj" />
    <ProjectReference Include="..\Lumyte.Graphics.Shader.Offline\Lumyte.Graphics.Shader.Offline.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Import Project="..\Lumyte.Graphics.Shader.Offline\Lumyte.Graphics.Shader.Offline.targets" />
</Project>
