using System.Numerics;
using Lumyte.Graphics.ModelPreparation;

namespace Lumyte.Graphics.Native.Passes.Tests;

public sealed class MikkTangentsTests
{
    [Theory]
    [InlineData(false,1,1)]
    [InlineData(true,-1,-1)]
    public void MirroredCoordinatesReverseTangentHandedness(bool mirrored,float direction,float sign)
    {
        Vector3[] positions=[Vector3.Zero,Vector3.UnitX,Vector3.UnitY];
        Vector2[] coordinates=[Vector2.Zero,new(mirrored ? -1 : 1,0),Vector2.UnitY];

        var tangents=MikkTangents.Generate(positions,[Vector3.UnitZ,Vector3.UnitZ,Vector3.UnitZ],coordinates);

        Assert.All(tangents,tangent=>Assert.Equal(new Vector4(direction,0,0,sign),tangent));
    }

    [Fact]
    public void DisconnectedIslandsDoNotShareTheTangentAtACoincidentVertex()
    {
        Vector3[] positions=[Vector3.Zero,Vector3.UnitX,Vector3.UnitY,Vector3.Zero,Vector3.UnitY,-Vector3.UnitX];
        Vector2[] coordinates=[Vector2.Zero,Vector2.UnitX,Vector2.UnitY,Vector2.Zero,Vector2.UnitX,Vector2.UnitY];

        var tangents=MikkTangents.Generate(positions,Enumerable.Repeat(Vector3.UnitZ,6).ToArray(),coordinates);

        Assert.Collection(new[] {tangents[0],tangents[3]},
            tangent=>Assert.Equal(new Vector4(1,0,0,1),tangent),tangent=>Assert.Equal(new Vector4(0,1,0,1),tangent));
    }

    [Fact]
    public void DegenerateFacesInheritMatchingHealthyCorners()
    {
        Vector3[] positions=[Vector3.Zero,Vector3.UnitX,Vector3.UnitY,Vector3.Zero,Vector3.Zero,Vector3.UnitX];
        Vector2[] coordinates=[Vector2.Zero,Vector2.UnitX,Vector2.UnitY,Vector2.Zero,Vector2.Zero,Vector2.UnitX];

        var tangents=MikkTangents.Generate(positions,Enumerable.Repeat(Vector3.UnitZ,6).ToArray(),coordinates);

        Assert.All(tangents,tangent=>Assert.Equal(new Vector4(1,0,0,1),tangent));
    }

    [Fact]
    public void ConnectedFacesMatchTheReferenceAngleWeightedTangent()
    {
        Vector3[] positions=[Vector3.Zero,new(-1,0,0),new(0,-1,.2f),new(1,0,.5f),new(0,1,-.3f)];
        Vector2[] coordinates=[new(.5f,.5f),new(0,.5f),new(.6f,1),new(1,.4f),new(.4f,0)];
        int[] indices=[0,1,2,0,2,3,0,3,4,0,4,1];
        var normals=Enumerable.Repeat(Vector3.Normalize(new Vector3(.2f,.3f,1)),12).ToArray();

        var tangents=MikkTangents.Generate(indices.Select(i=>positions[i]).ToArray(),normals,indices.Select(i=>coordinates[i]).ToArray());

        // Independently generated by the reference C implementation; see model-tangent-validation.md.
        var expected=new Vector4(.9652849f,-.22983155f,-.124107525f,-1);
        Assert.All(new[] {tangents[0],tangents[3],tangents[6],tangents[9]},
            tangent=>Assert.True(Vector4.Distance(expected,tangent)<1e-6f,$"Expected {expected}, actual {tangent}."));
    }
}
