<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lumyte.Input/Lumyte.Input.csproj" />
    <ProjectReference Include="../Lumyte.Input.Processing/Lumyte.Input.Processing.csproj" />
    <ProjectReference Include="../Lumyte.Input.Actions/Lumyte.Input.Actions.csproj" />
    <ProjectReference Include="../../Core/Lumyte.Settings/Lumyte.Settings.csproj" />
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
