<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>WebGPU implementation of Lumyte Graphics.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lumyte.Graphics\Lumyte.Graphics.csproj" />
    <ProjectReference Include="..\Lumyte.Graphics.Portable\Lumyte.Graphics.Portable.csproj" />
    <PackageReference Include="WebGPUSharp" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Lumyte.Graphics.WebGPU.Tests" />
  </ItemGroup>
</Project>
