import {Badge,Button,MessageBar,MessageBarBody,MessageBarTitle,Table,TableBody,TableCell,TableHeader,TableHeaderCell,TableRow,Text,makeStyles,tokens} from '@fluentui/react-components';
import {bytes,duration,number} from '../utils/format';
const useStyles=makeStyles({id:{fontFamily:tokens.fontFamilyMonospace,maxWidth:'18rem',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',display:'inline-block',verticalAlign:'bottom'},badges:{display:'flex',gap:tokens.spacingHorizontalXS,flexWrap:'wrap'},details:{marginTop:tokens.spacingVerticalM}});
const label=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,v=>v.toUpperCase());
export function CopyableId({value}:{value:string}){const s=useStyles();return <span><Text className={s.id} title={value}>{value}</Text><Button appearance="subtle" size="small" aria-label={`Copy ${value}`} onClick={()=>void navigator.clipboard.writeText(value)}>Copy</Button></span>}
export function HumanValue({name,value}:{name?:string;value:unknown}){const s=useStyles();if(value==null)return <Text>—</Text>;if(typeof value==='boolean')return <Badge appearance="tint" color={value?'success':'subtle'}>{value?'Yes':'No'}</Badge>;if(typeof value==='number'){if(/bytes/i.test(name??''))return <Text>{bytes(value)}</Text>;if(/duration|milliseconds|remaining/i.test(name??''))return <Text>{duration(value)}</Text>;return <Text>{number(value)}</Text>}if(typeof value==='string'){if(/id$|trace|parent/i.test(name??'')||value.length>48)return <CopyableId value={value}/>;if(/time|date|start|timestamp|at$/i.test(name??'')&&!Number.isNaN(Date.parse(value)))return <Text>{new Date(value).toLocaleString()}</Text>;return <Text>{value||'—'}</Text>}if(Array.isArray(value))return <span className={s.badges}>{value.length?value.slice(0,12).map((item,i)=><Badge key={i} appearance="outline">{typeof item==='object'?itemLabel(item):String(item)}</Badge>):<Text>None</Text>}{value.length>12&&<Badge>+{value.length-12}</Badge>}</span>;return <details className={s.details}><summary>Raw details</summary><ObjectDetails value={value as Record<string,unknown>}/></details>}
const itemLabel=(item:unknown)=>{if(!item||typeof item!=='object')return String(item);const r=item as Record<string,unknown>;return String(r.name??r.key??r.id??r.control??r.action??'Item')};
export function ObjectDetails({value,exclude=[]}:{value:Record<string,unknown>;exclude?:string[]}){const entries=Object.entries(value).filter(([k])=>!exclude.includes(k));return <Table size="small" aria-label="Details"><TableHeader><TableRow><TableHeaderCell>Property</TableHeaderCell><TableHeaderCell>Value</TableHeaderCell></TableRow></TableHeader><TableBody>{entries.map(([key,item])=><TableRow key={key}><TableCell><Text weight="semibold">{label(key)}</Text></TableCell><TableCell><HumanValue name={key} value={item}/></TableCell></TableRow>)}</TableBody></Table>}
export function RecordTable({items,label:ariaLabel}:{items:unknown;label:string}){if(items!=null&&!Array.isArray(items))return <MessageBar intent="error"><MessageBarBody><MessageBarTitle>{ariaLabel} unavailable</MessageBarTitle>The runtime returned an unexpected data shape.</MessageBarBody></MessageBar>;const records=(Array.isArray(items)?items:[]).filter(x=>x&&typeof x==='object') as Record<string,unknown>[];const keys=[...new Set(records.flatMap(Object.keys))].filter(k=>!records.some(r=>typeof r[k]==='object'&&r[k]!==null)).slice(0,7);if(!records.length)return <Text>No {ariaLabel.toLowerCase()}.</Text>;return <Table aria-label={ariaLabel}><TableHeader><TableRow>{keys.map(k=><TableHeaderCell key={k}>{label(k)}</TableHeaderCell>)}</TableRow></TableHeader><TableBody>{records.map((r,i)=><TableRow key={String(r.id??r.key??r.name??i)}>{keys.map(k=><TableCell key={k}><HumanValue name={k} value={r[k]}/></TableCell>)}</TableRow>)}</TableBody></Table>}
