<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lumyte.Graphics\Lumyte.Graphics.csproj" />
    <ProjectReference Include="..\Lumyte.Graphics.Vulkan\Lumyte.Graphics.Vulkan.csproj" />
    <ProjectReference Include="..\Lumyte.Platform\Lumyte.Platform.csproj" />
    <ProjectReference Include="..\Lumyte.Platform.Silk\Lumyte.Platform.Silk.csproj" />
    <ProjectReference Include="..\Lumyte.Shaders\Lumyte.Shaders.csproj" />
    <PackageReference Include="Silk.NET.Shaderc" />
    <PackageReference Include="Silk.NET.Vulkan" />
  </ItemGroup>
</Project>
