<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Lumyte.Graphics.Abstractions/Lumyte.Graphics.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../../tools/shaders/include/lumyte.slang" LogicalName="Lumyte.Shaders.lumyte.slang" />
  </ItemGroup>
</Project>
