using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Lumyte.Graphics.Native.Shaders.Offline;

internal static class NativeShaderGeneration
{
    internal static void ValidateNames(NativeShaderBuildRequest request)
    {
        foreach (string part in request.HostNamespace.Split('.')) { Identifier(part); }
        foreach (NativeShaderEntryPoint entry in request.EntryPoints) { Identifier(entry.Name); }
        var generatedNames = new HashSet<string>(StringComparer.Ordinal) { "Root", "RootResources" };
        foreach (string type in request.ParameterTypes)
        {
            foreach (string part in type.Split("::", StringSplitOptions.None)) { Identifier(part); }
            string hostType = type.Replace("::", "_", StringComparison.Ordinal);
            if (!generatedNames.Add(hostType) || !generatedNames.Add(hostType + "Resources"))
            {
                throw new ArgumentException($"Parameter type '{type}' collides with a generated host or Resources input type.", nameof(request));
            }
        }
        foreach (string define in request.Defines.Keys) { Identifier(define); }
    }

    internal static void Identifier(string name)
    {
        if (!Regex.IsMatch(name, "^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.CultureInvariant))
        {
            throw new ArgumentException($"'{name}' is not a supported shader/host identifier.");
        }
    }

    private static string Namespace(string value) => string.Join('.', value.Split('.').Select(part => "@" + part));
    private static string Q(string value) => JsonSerializer.Serialize(value);

    internal static void AddLayout(string hostNamespace, NativeShaderTarget target, NativeReflectedLayout layout,
        string hash, IDictionary<string, string> sources, IDictionary<string, string> inputs)
    {
        string ns = hostNamespace + "." + target;
        string name = layout.Name;
        Identifier(name);
        if (layout.HostFields.Any(f => f.Type == name && f.Type.StartsWith("Bytes", StringComparison.Ordinal)))
        {
            throw new InvalidDataException($"Input type '{name}' collides with its generated byte storage helper.");
        }
        if (layout.HostFields.Any(f => f.Name is "ByteSize" or "AbiHash" || f.Name == name || f.Name.StartsWith("Bytes", StringComparison.Ordinal)))
        {
            throw new InvalidDataException("A shader field collides with a generated host member.");
        }
        var text = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace ").Append(Namespace(ns)).AppendLine(";");
        text.Append("[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = ")
            .Append(Math.Max(1, layout.Size)).AppendLine(")]");
        text.Append("public struct @").Append(name).AppendLine("\n{");
        text.Append("    public const uint ByteSize = ").Append(layout.Size).AppendLine(";");
        text.Append("    public const string AbiHash = ").Append(Q(hash)).AppendLine(";");
        foreach (NativeHostField field in layout.HostFields)
        {
            text.Append("    [global::System.Runtime.InteropServices.FieldOffset(").Append(field.Offset).Append(")] public ")
                .Append(field.Type).Append(" @").Append(field.Name).AppendLine(";");
        }
        foreach (NativeHostField blob in layout.HostFields.Where(f => f.Type.StartsWith("Bytes", StringComparison.Ordinal)).DistinctBy(f => f.Type))
        {
            text.Append("    [global::System.Runtime.CompilerServices.InlineArray(").Append(blob.Size).Append(")] public struct ")
                .Append(blob.Type).AppendLine(" { private byte first; }");
        }
        text.AppendLine("}");
        sources.Add(target + "." + name + ".g.cs", text.ToString());
        var xml = new XElement("input", new XAttribute("namespace", ns), new XAttribute("name", name + "Resources"),
            new XAttribute("size", layout.Size), new XAttribute("abiHash", hash));
        foreach (NativeShaderInputField field in layout.Fields.Where(f => f.ResourceKind != NativeShaderResourceKind.None))
        {
            var element = new XElement("field", new XAttribute("name", field.Name), new XAttribute("kind", field.Kind), new XAttribute("offset", field.Offset));
            if (field.Kind == NativeShaderInputFieldKind.DescriptorIndex) { element.Add(new XAttribute("resource", field.ResourceKind)); }
            xml.Add(element);
        }
        inputs.Add(target + "." + name + ".native.resources.xml", xml.ToString());
    }

    internal static byte[] PackageBytes(NativeShaderPackage package, string compilerVersion)
        => JsonSerializer.SerializeToUtf8Bytes(new
        {
            Format = "Lumyte.Native.Shader", package.Version, CompilerVersion = compilerVersion,
            Artifacts = package.Artifacts.Select(a => new
            {
                a.Target, a.CodeFormat, a.RequiredCapabilities, a.DescriptorHeapAbi, a.RootLayout, a.ParameterLayouts, a.AbiHash,
                Stages = a.Stages.Select(s => new { s.Stage, s.EntryPoint, Code = Convert.ToBase64String(s.Code) }),
            }),
        });

    internal static string PackageFactory(string hostNamespace, NativeShaderPackage package)
    {
        var text = new StringBuilder("// <auto-generated/>\n#nullable enable\nusing Lumyte.Graphics;\nusing Lumyte.Graphics.Native.Shaders;\nnamespace ")
            .Append(Namespace(hostNamespace)).AppendLine(";");
        text.AppendLine("public static class ShaderPackage\n{\n    public static NativeShaderPackage Create() => new(NativeShaderPackage.CurrentVersion, new NativeShaderArtifact[]\n    {");
        foreach (NativeShaderArtifact artifact in package.Artifacts)
        {
            text.Append("        new(NativeShaderTarget.").Append(artifact.Target).Append(", GpuShaderCodeFormat.").Append(artifact.CodeFormat)
                .AppendLine(", new NativeShaderStageArtifact[]\n        {");
            foreach (NativeShaderStageArtifact stage in artifact.Stages)
            {
                text.Append("            new(GpuShaderStage.").Append(stage.Stage).Append(", ").Append(Q(stage.EntryPoint))
                    .Append(", global::System.Convert.FromBase64String(").Append(Q(Convert.ToBase64String(stage.Code))).AppendLine(")),");
            }
            text.Append("        }, (NativeShaderCapabilities)").Append(((uint)artifact.RequiredCapabilities).ToString(CultureInfo.InvariantCulture))
                .Append(", new NativeShaderDescriptorHeapAbi(NativeShaderDescriptorHeapAbiKind.").Append(artifact.DescriptorHeapAbi.Kind)
                .Append(", ").Append(artifact.DescriptorHeapAbi.Version).Append("), ");
            WriteLayout(text, artifact.RootLayout);
            text.Append(", new NativeShaderInputLayout[] { ");
            foreach (NativeShaderInputLayout layout in artifact.ParameterLayouts) { WriteLayout(text, layout); text.Append(", "); }
            text.Append("}, ").Append(Q(artifact.AbiHash)).AppendLine("),");
        }
        return text.AppendLine("    });\n}").ToString();
    }

    private static void WriteLayout(StringBuilder text, NativeShaderInputLayout layout)
    {
        text.Append("new NativeShaderInputLayout(").Append(Q(layout.AbiId)).Append(", ").Append(layout.Size).Append(", ")
            .Append(layout.Alignment).Append(", new NativeShaderInputField[] { ");
        foreach (NativeShaderInputField field in layout.Fields)
        {
            text.Append("new(").Append(Q(field.Name)).Append(", NativeShaderInputFieldKind.").Append(field.Kind).Append(", ")
                .Append(field.Offset).Append(", ").Append(field.Size).Append(", NativeShaderResourceKind.").Append(field.ResourceKind).Append("), ");
        }
        text.Append("})");
    }
}
