<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DevelopmentDependency>true</DevelopmentDependency>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DefineConstants>$(DefineConstants);LUMYTE_NATIVE</DefineConstants>
    <Description>Build-time Native managed shader reference inputs from prepared metadata.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <Compile Include="../Lumyte.Graphics.Resources.Generators.Shared/ResourceInputGenerator.cs" Link="ResourceInputGenerator.cs" />
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md;AnalyzerReleases.Unshipped.md" />
    <None Update="buildTransitive/Lumyte.Graphics.Native.Resources.Generators.targets" Pack="true" PackagePath="buildTransitive/Lumyte.Graphics.Native.Resources.Generators.targets" />
    <None Update="README.md" Pack="true" PackagePath="/" />
    <None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs/" Visible="false" />
  </ItemGroup>
</Project>
