<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmEnableHotReload>false</WasmEnableHotReload>
    <WasmBuildNative>false</WasmBuildNative>
    <RunAOTCompilation>false</RunAOTCompilation>
    <WasmFingerprintAssets>false</WasmFingerprintAssets>
    <PublishTrimmed>false</PublishTrimmed>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Lumyte.Graphics.WebGPU.Browser\Lumyte.Graphics.WebGPU.Browser.csproj" />
    <ProjectReference Include="..\..\..\Lumyte.Graphics.Portable.Shaders\Lumyte.Graphics.Portable.Shaders.csproj" />
    <ProjectReference Include="..\..\..\Lumyte.Graphics.Portable.Resources\Lumyte.Graphics.Portable.Resources.csproj" />
    <Content Include="..\..\..\Lumyte.Graphics.WebGPU.Browser\wwwroot\lumyte-webgpu.js" Link="wwwroot\lumyte-webgpu.js" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
