<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lumyte.Graphics.DirectX12\Lumyte.Graphics.DirectX12.csproj" />
    <ProjectReference Include="..\Lumyte.Shaders\Lumyte.Shaders.csproj" />
    <PackageReference Include="Microsoft.Direct3D.DXC" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
  <ItemGroup>
    <None Include="$(PkgMicrosoft_Direct3D_DXC)\build\native\bin\x64\dxc.exe" Link="dxc.exe" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(PkgMicrosoft_Direct3D_DXC)\build\native\bin\x64\dxcompiler.dll" Link="dxcompiler.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(PkgMicrosoft_Direct3D_DXC)\build\native\bin\x64\dxil.dll" Link="dxil.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
