<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Graphics Wgpu device capabilities.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
    <ProjectReference Include="../Lumyte.Graphics.Abstractions/Lumyte.Graphics.Abstractions.csproj" />
    <PackageReference Include="Ahjo.Wgpu" Version="0.7.0" />
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
