<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>HarfBuzz-based text shaping and adaptive two-dimensional text rendering for Lumyte.</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Lumyte.Graphics.Text.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lumyte.Graphics.TwoD\Lumyte.Graphics.TwoD.csproj" />
    <PackageReference Include="HarfBuzzSharp" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.WebAssembly" />
  </ItemGroup>
</Project>
