using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lumyte.Graphics.Generators;

/// <summary>Generates direct AOT-safe shader member readers for application structures.</summary>
[Generator]
public sealed class ShaderCodecGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor _unsupported = new(
        "LUMG001", "Unsupported shader value", "Shader codec cannot serialize '{0}': {1}", "Lumyte.Graphics", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol?> types = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax declaration && (declaration.AttributeLists.Count != 0 || declaration.BaseList != null),
            static (syntax, token) => syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, token) as INamedTypeSymbol);
        context.RegisterSourceOutput(types.Collect(), static (output, candidates) =>
        {
            var emitted = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
            foreach (INamedTypeSymbol? type in candidates)
            {
                if (type != null && emitted.Add(type))
                {
                    Emit(output, type);
                }
            }
        });
    }

    private static void Emit(SourceProductionContext output, INamedTypeSymbol? type)
    {
        if (type == null || type.TypeKind != TypeKind.Struct)
        {
            return;
        }

        AttributeData? root = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Lumyte.Graphics.Abstractions.ShaderArgumentsAttribute");
        bool data = type.AllInterfaces.Any(i => i.ToDisplayString() == "Lumyte.Graphics.Abstractions.IShaderData");
        if (root == null && !data)
        {
            return;
        }

        if (type.IsGenericType || type.ContainingType != null || type.DeclaredAccessibility == Accessibility.Private)
        {
            Report(output, type, "generic or nested codec types are not supported");
            return;
        }

        var body = new StringBuilder();
        if (!Members(output, type, "value", string.Empty, body, new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default)))
        {
            return;
        }

        string qualified = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string rootName = root?.ConstructorArguments.Length > 0 ? root.ConstructorArguments[0].Value as string ?? "arguments" : "arguments";
        AttributeData? nameAttribute = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Lumyte.Graphics.Abstractions.ShaderTypeNameAttribute");
        string shaderName = nameAttribute?.ConstructorArguments[0].Value as string ?? type.Name;
        string id = new string(type.ToDisplayString().Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
        string source = "// <auto-generated/>\n#nullable enable\n#pragma warning disable CA2255\nnamespace Lumyte.Graphics.Generated;\n" +
            "internal static class Codec_" + id + "\n{\n" +
            "    [global::System.Runtime.CompilerServices.ModuleInitializer]\n    internal static void Register()\n    {\n" +
            "        global::Lumyte.Graphics.Abstractions.ShaderCodec<" + qualified + ">.Register(" + Quote(rootName) + ", " + Quote(shaderName) + ", Write);\n    }\n" +
            "    private static void Write(in " + qualified + " value, global::Lumyte.Graphics.Abstractions.IShaderValueWriter writer)\n    {\n" + body + "    }\n}\n";
        output.AddSource("ShaderCodec_" + id + ".g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static bool Members(SourceProductionContext output, INamedTypeSymbol type, string expression, string prefix, StringBuilder body, HashSet<ITypeSymbol> stack)
    {
        if (!stack.Add(type))
        {
            Report(output, type, "inline member cycle");
            return false;
        }

        foreach (ISymbol member in type.GetMembers().Where(m => !m.IsStatic && m.DeclaredAccessibility == Accessibility.Public))
        {
            ITypeSymbol? memberType = member is IFieldSymbol field ? field.Type : member is IPropertySymbol property && !property.IsIndexer && property.GetMethod != null ? property.Type : null;
            if (memberType == null)
            {
                continue;
            }

            if (member is IPropertySymbol p && p.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is PropertyDeclarationSyntax syntax &&
                (syntax.ExpressionBody != null || syntax.AccessorList?.Accessors.Any(a => a.Body != null || a.ExpressionBody != null) == true)))
            {
                Report(output, member, "custom getters are not supported");
                return false;
            }

            string path = prefix + member.Name;
            string access = expression + ".@" + member.Name;
            if (memberType is INamedTypeSymbol reference && reference.OriginalDefinition.ToDisplayString() == "Lumyte.Graphics.Abstractions.IGpuRef<T>")
            {
                body.Append("        writer.WriteReference(").Append(Quote(path)).Append(", ").Append(access).AppendLine(");");
            }
            else if (Numeric(memberType))
            {
                body.Append("        writer.WriteValue(").Append(Quote(path)).Append(", ").Append(access).AppendLine(");");
            }
            else if (memberType is INamedTypeSymbol nested && nested.TypeKind == TypeKind.Struct && nested.SpecialType == SpecialType.None && !nested.IsGenericType)
            {
                if (!Members(output, nested, access, path + ".", body, stack))
                {
                    return false;
                }
            }
            else
            {
                Report(output, member, "unsupported member type " + memberType.ToDisplayString());
                return false;
            }
        }

        stack.Remove(type);
        return true;
    }

    private static bool Numeric(ITypeSymbol type) => type.SpecialType is SpecialType.System_Int32 or SpecialType.System_UInt32 or SpecialType.System_Single ||
        type.ToDisplayString() is "System.Numerics.Vector2" or "System.Numerics.Vector3" or "System.Numerics.Vector4" or "System.Numerics.Matrix4x4";

    private static string Quote(string value) => SymbolDisplay.FormatLiteral(value, true);

    private static void Report(SourceProductionContext output, ISymbol symbol, string reason) => output.ReportDiagnostic(Diagnostic.Create(_unsupported, symbol.Locations.FirstOrDefault(), symbol.Name, reason));
}
